# Empty field is the same as None

max_age: 30                 # Default: 1
min_hits: 30                # Default: 3
iou_threshold: 0.1          # Default: 0.3
EWMA_alpha: 0.1             # Default: 0.2
std_pos: 0.5                # Default: 0.5e-2
std_vel: 6.25e-3            # Default: 6.25e-3