topics:
  input:
    safe_points_world_coord: "/segmentation/safe_points/world_frame"
    tracks_world_coord: "/search/tracks/world_coordinates"
    platform_EKF: "/estimate/ekf"

  output:
    detected_person: "/perception/detected_person"
    safe_point: "/perception/safe_point"

services:
  AT_node_activation_name: activate_AT_tracking
  DNN_node_activation_name: activate_DNN_tracking
  GNSS_node_activation_name: activate_GNSS_tracking

settings:
  min_dist_to_initiate_platform_tracking: 10
  radius_of_acceptance_new_human_detections: 5
  radius_of_acceptance_new_FO_detections: 5
  critical_level_distances: [0, 5, 30]
  track_confidence_threshold: 0.8
  radius_of_acceptance_new_safe_points: 0.2