# Following the notation in Fossen 2021

std_msgs/Header header

float32 x_ref     # x-position  [m] 
float32 y_ref     # y-position  [m]
float32 z_ref     # z-position  [m]
float32 phi_ref   # roll        [rad]      
float32 theta_ref # pitch       [rad]     
float32 psi_ref   # yaw         [rad]

float32 u_ref     # surge       [m/s]
float32 v_ref     # sway        [m/s]
float32 w_ref     # heave       [m/s]
float32 p_ref     # roll rate   [rad/s]   
float32 q_ref     # pitch rate  [rad/s]   
float32 r_ref     # yaw rate    [rad/s]   
