topics:
  input:
    image: "/anafi/image"
  output:
    boxes: "/yolo/search/boxes"
    detectionImage: "/yolo/search/detectionImage"

publish_detected_image: True

settings:
  class_names: ["human", "floating-objects"]
  AT_ids: [10, 11]
  detection_confidence: 0.81


