topics:
  input:
    image: "/anafi/image"
  output:
    water_mask: "/debug/segmentation_dl_mask"

model_settings:
  model_path: "/home/msccomputer/catkin_ws/src/msc_thesis/water_segmentation/data/segmentation_models/SegNet_rmsprop.pth"
  classes: 1
  bilinear: False
  model_type: "segnet"
  
services:
  make_mask: make_dl_mask

debug: False 