offline_map: 
  map_resolution_px:
    width: 5000
    height: 5000
  map_radius: 100
  shapefile_path: "/home/msccomputer/catkin_ws/src/msc_thesis/water_segmentation/data/trondheim_water/trondheim_water.shp"

topics:
  input:
    gnss: "/anafi/gnss_location"
    drone_pose: "/anafi/pose"
    drone_image: "/anafi/image" # Only used for debugging
  output: 
    water_mask: "/segmentation/offline_mask"

services:
  make_mask: make_offline_mask

debug: False