topics:
  input:
    tracks: "/search/tracks"
    rpy: "/qualisys/Anafi/pose"
    NED_gnss: "/qualisys/Anafi/pose"
  output:
    track_world_coordinate: "/search/tracks/world_coordinates"
    track_camera_coordinate_triangulate: "/search/tracks/camera_coordinates_tria"
    track_camera_coordinate_fov: "/search/tracks/camera_coordinates_fov"

flags:
  publish_camera_coordinates: True