topics:
  input:
    tracks: "/search/tracks"
    pose: "/anafi/pose"
    NED_gnss: "/anafi/ned_pos_from_gnss"
  output:
    track_world_coordinate: "/search/tracks/world_coordinates"
    track_camera_coordinate_triangulate: "/search/tracks/camera_coordinates_tria"
    track_camera_coordinate_fov: "/search/tracks/camera_coordinates_fov"

flags:
  publish_camera_coordinates: True