topics:
  input:
    tracks: "/search/tracks"
    safe_points_cam_frame: "/segmentation/safe_points/image_coordinates"
  output:
    track_world_coordinate: "/search/tracks/world_coordinates"
    track_camera_coordinate_triangulate: "/search/tracks/camera_coordinates_tria"
    track_camera_coordinate_fov: "/search/tracks/camera_coordinates_fov"
    safe_point_world_coordinate: "/segmentation/safe_points/world_frame"

flags:
  debug: True